name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 1sdc0d3r/devops-starwars
      # :$(date +%s)

    - name: Login to Docker Hub
      run: docker login -u 1sdc0d3r -p ${{ secrets.DOCKER_HUB_TOKEN }} docker.io

    - name: Push Docker image to docker hub
      run: docker push 1sdc0d3r/devops-starwars
      # not pushing with tag currently
